### ISSUE TITLE
docker error: no space left on device

### ISSUE THREAD

**Issue by DinisCruz** [avatao-content/challenge-toolbox#11]
When running ```python3 ./build.py templates/xss```

I believe this is an issue with my docker machine (I will purge some tmp files)

**Comment by DinisCruz** [comment]
doing a bunch of ```docker rmi ``` and ```docker rm``` fixed it

**Comment by DinisCruz** [comment]
Here are a bunch of docker helper scripts 
https://github.com/avatao-content/challenge-toolbox/blob/master/docker-cleanup.sh

**Comment by MrBlaise** [comment]
Thanks! I close this since this is solved for you.
